#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TripXpense.Android.Resource", IsApplication=true)]

namespace TripXpense.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001f
			public const int Text = 2131034143;
			
			// aapt resource value: 0x7f050022
			public const int TripAmount = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int TripDate = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int TripName = 2131034144;
			
			// aapt resource value: 0x7f05000e
			public const int editExpenseButtonDelete = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int editExpenseButtonSave = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int editExpenseDatePickerDate = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int editExpenseEditTextAmount = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int editExpenseEditTextTitle = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int editExpenseLayout = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int editExpenseTextViewAmount = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int editExpenseTextViewSpentOn = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int editExpenseTextViewTitle = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int editExpenseTextViewTripBudget = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int editExpenseTextViewTripDesc = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int editExpenseTextViewTripName = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int editExpenseTextViewpTripDate = 2131034116;
			
			// aapt resource value: 0x7f05001b
			public const int editTripButtonDelete = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int editTripButtonSave = 2131034138;
			
			// aapt resource value: 0x7f050015
			public const int editTripDatePickerEnd = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int editTripDatePickerStart = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int editTripEditTextBudget = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int editTripEditTextDesc = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int editTripEditTextTripName = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int editTripScrollView = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int editTripTextViewTripName = 2131034128;
			
			// aapt resource value: 0x7f05001d
			public const int homeInnerRelativeLayout = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int homeListViewTrips = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int homebuttonAddTrip = 2131034142;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int textExpenses = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int textView2 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int textView3 = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int textView4 = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int textView5 = 2131034136;
			
			// aapt resource value: 0x7f05002b
			public const int viewTripDetaiButtonAdd = 2131034155;
			
			// aapt resource value: 0x7f05002f
			public const int viewTripDetailExpenseAmount = 2131034159;
			
			// aapt resource value: 0x7f05002d
			public const int viewTripDetailExpenseDate = 2131034157;
			
			// aapt resource value: 0x7f05002c
			public const int viewTripDetailExpenseListLayout = 2131034156;
			
			// aapt resource value: 0x7f05002e
			public const int viewTripDetailExpenseName = 2131034158;
			
			// aapt resource value: 0x7f050024
			public const int viewTripDetailLayout = 2131034148;
			
			// aapt resource value: 0x7f050029
			public const int viewTripDetailListViewExpenses = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int viewTripDetailTextViewBudget = 2131034152;
			
			// aapt resource value: 0x7f050026
			public const int viewTripDetailTextViewDesc = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int viewTripDetailTextViewTripDate = 2131034151;
			
			// aapt resource value: 0x7f050025
			public const int viewTripDetailTextViewTripName = 2131034149;
			
			// aapt resource value: 0x7f05002a
			public const int viewTripDetailTotalExpense = 2131034154;
			
			// aapt resource value: 0x7f050023
			public const int viewTripDetailscrollView = 2131034147;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditExpense = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditTrip = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HomeTripsList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ViewTripDetail = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ViewTripDetailExpenseList = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
